# Generated by Django 4.0.3 on 2022-04-03 17:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='battler',
        ),
        migrations.AddField(
            model_name='battle',
            name='battler',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
