# Generated by Django 4.0.3 on 2022-04-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_battle_battler_battle_battler'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battle',
            old_name='battler',
            new_name='battlers',
        ),
    ]
